### ISSUE TITLE
Can't build Steam Database + RimSort Crashes

### ISSUE THREAD

**Issue by Lorsieab2** [RimSort/RimSort#1630]
### Release Type

Compiled (Windows x86-64)

### Version

1.0.63

### Operating System

Windows 11

### Relevant logs

https://0x0.st/PzIH.old.log

### Describe the bug

I'm trying to build the Steam Workshop database. When I get the PublishedFileIDs from the Workshop, RimSort crashes and there's a 503 Service Unavailable error in the log. https://0x0.st/PzIH.old.log

### Code of Conduct

I agree to follow this project's Code of Conduct

### Duplicate Issue Check

I've checked for similar issues and didn't find anything

### Wiki/FAQ Check

I've checked the Wiki for a solution and didn't find a solution

**Comment by cebarks** [comment]
Is this still persisting? i just ran a full webapi db build and it worked fine.

Nonetheless, RimSort should be failing gracefully instead of crashing if it fails...

**Comment by LionelColaso** [comment]
@Lorsieab2 as per the error

```
[INFO][2025-12-24 16:53:55][7660][Dummy-22][dialogue][show_fatal_error][269] : Showing fatal error box with input: [RimSort crashed], [The RimSort application crashed! Sorry for the inconvenience!], [Please contact us on the Discord/Github to report the issue.], [Traceback (most recent call last):
  File "C:\PROGRA~2\RimSort\app\utils\metadata.py", line 2737, in run
  File "C:\PROGRA~2\RimSort\app\utils\db_builder_core.py", line 86, in run
  File "C:\PROGRA~2\RimSort\app\utils\steam\webapi\wrapper.py", line 438, in pfids_by_appid
  File "C:\PROGRA~2\RimSort\app\utils\steam\webapi\wrapper.py", line 640, in IPublishedFileService_QueryFiles
  File "C:\PROGRA~2\RimSort\steam\webapi.py", line 167, in call
  File "C:\PROGRA~2\RimSort\steam\webapi.py", line 327, in __call__
  File "C:\PROGRA~2\RimSort\steam\webapi.py", line 431, in webapi_request
  File "C:\PROGRA~2\RimSort\requests\models.py", line 1026, in raise_for_status
requests.exceptions.HTTPError: 503 Server Error: Service Unavailable for url
]
```

it could be a temp issue, try again if it is not fixed see here to fix on your side https://www.geeksforgeeks.org/blogs/http-error-503-service-unavailable-fix/

**Comment by cykonetic** [comment]
I have been getting a similar error since version 65. I am still getting it in 67. My latest log has a different error than this, however.
```
[ERROR][2026-01-14 18:37:44][2040][Dummy-47][__main__][handle_exception][75] : The main application loop has failed with an uncaught exception
[INFO][2026-01-14 18:37:44][2040][Dummy-47][dialogue][show_fatal_error][269] : Showing fatal error box with input: [RimSort crashed], [The RimSort application crashed! Sorry for the inconvenience!], [Please contact us on the Discord/Github to report the issue.], [multiprocessing.pool.RemoteTraceback: 
"""
Traceback (most recent call last):
  File "C:\Users\...\WORKSP~1\RimSort\multiprocessing\pool.py", line 125, in worker
  File "C:\Users\...\WORKSP~1\RimSort\multiprocessing\pool.py", line 48, in mapstar
  File "C:\Users\...\WORKSP~1\RimSort\app\utils\steam\steamworks\wrapper.py", line 198, in run
  File "C:\Users\...\WORKSP~1\RimSort\steamworks\interfaces\workshop.py", line 89, in SetGetAppDependenciesResultCallback
ctypes.ArgumentError: argument 1: TypeError: expected CFunctionType instance instead of CFunctionType
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\...\WORKSP~1\RimSort\app\utils\metadata.py", line 2777, in run
  File "C:\Users\...\WORKSP~1\RimSort\app\utils\steam\webapi\wrapper.py", line 411, in create_steam_db
  File "C:\Users\...\WORKSP~1\RimSort\app\utils\steam\webapi\wrapper.py", line 740, in ISteamUGC_GetAppDependencies
  File "C:\Users\...\WORKSP~1\RimSort\multiprocessing\pool.py", line 367, in map
  File "C:\Users\...\WORKSP~1\RimSort\multiprocessing\pool.py", line 774, in get
ctypes.ArgumentError: argument 1: TypeError: expected CFunctionType instance instead of CFunctionType
]
[INFO][2026-01-14 18:37:44][2040][Dummy-47][dialogue][exec][345] : Showing base dialogue box with title: RimSort crashed

```
The error box does not render.

**Comment by LionelColaso** [comment]
@cykonetic can i get a full RimSort.log for this after enabling Debug in settings

**Comment by cykonetic** [comment]
Sure.
I suspect the same class exists on two namespaces and the one imported by your code doesn't match the one in the library.
[RimLog](https://github.com/cykonetic/Rimsort-Troubleshoot/blob/main/rimlog.txt)

**Comment by cykonetic** [comment]
https://0x0.st/PqAf.old.log

**Comment by cykonetic** [comment]
https://0x0.st/PbrD.old.log

**Comment by prizrak1609** [comment]
I see the same crash on MacOS with RimSort v1.0.69
Crash: https://pastebin.pl/view/f591f5d0

**Comment by prizrak1609** [comment]
Logs: https://0x0.st/PboP.log

**Comment by Skydea777** [comment]
Still happening, and the official SteamDatabase listing is over three months old which makes all this frustrating, each time I try to update my mods.... crash, and 50 more mods were deleted... *groan*

`Traceback (most recent call last):
  File "D:\_Programme\RimSort\app\utils\metadata.py", line 2074, in run
  File "D:\_Programme\RimSort\app\utils\db_builder_core.py", line 84, in run
  File "D:\_Programme\RimSort\app\utils\steam\webapi\wrapper.py", line 408, in pfids_by_appid
  File "D:\_Programme\RimSort\app\utils\steam\webapi\wrapper.py", line 582, in IPublishedFileService_QueryFiles
  File "D:\_Programme\RimSort\steam\webapi.py", line 167, in call
  File "D:\_Programme\RimSort\steam\webapi.py", line 309, in __call__
ValueError: Method requires 'special_filter' to be set
`

`
[INFO][2026-05-06 21:30:52][35760][MainThread][main_content_panel][_do_build_database_thread][2681] : Selected path: C:\Users\...\AppData\Local\RimSort\dbs\Steam-API-Database\Steam-API-Database_NEW_20260506.json
[DEBUG][2026-05-06 21:30:52][35760][MainThread][runner_panel][__init__][61] : Initializing RunnerPanel
[INFO][2026-05-06 21:30:52][35760][Dummy-719][wrapper][__init__][257] : Initializing DynamicQuery
[DEBUG][2026-05-06 21:30:52][35760][Dummy-719][wrapper][__initialize_webapi][305] : WebAPI is not active!
[DEBUG][2026-05-06 21:30:52][35760][MainThread][runner_panel][message][362] : 
Initiating RimSort Steam Database Builder with mode : no_local

[DEBUG][2026-05-06 21:30:52][35760][MainThread][runner_panel][message][362] : Received valid Steam WebAPI key
[DEBUG][2026-05-06 21:30:52][35760][MainThread][runner_panel][message][362] : 
Initializing "DynamicQuery" with configured Steam API key for AppID: 294100


[ERROR][2026-05-06 21:30:53][35760][Dummy-719][__main__][handle_exception][77] : The main application loop has failed with an uncaught exception
[INFO][2026-05-06 21:30:53][35760][Dummy-719][dialogue][show_fatal_error][261] : Showing fatal error box with input: [RimSort crashed], [The RimSort application crashed! Sorry for the inconvenience!], [Please contact us on the Discord/Github to report the issue.], [Traceback (most recent call last):
  File "D:\_Programme\RimSort\app\utils\metadata.py", line 2074, in run
  File "D:\_Programme\RimSort\app\utils\db_builder_core.py", line 84, in run
  File "D:\_Programme\RimSort\app\utils\steam\webapi\wrapper.py", line 408, in pfids_by_appid
  File "D:\_Programme\RimSort\app\utils\steam\webapi\wrapper.py", line 582, in IPublishedFileService_QueryFiles
  File "D:\_Programme\RimSort\steam\webapi.py", line 167, in call
  File "D:\_Programme\RimSort\steam\webapi.py", line 309, in __call__
ValueError: Method requires 'special_filter' to be set
]
[INFO][2026-05-06 21:30:53][35760][Dummy-719][dialogue][exec][329] : Showing base dialogue box with title: RimSort crashed
`

**Comment by cebarks** [comment]
this should be fixed in this PR #1938

**Comment by Skydea777** [comment]
@cebarks 

The Data gets Synced but upon entering the Last Phase at 100% (The part where it says I have to wait) nothing happens for over two hours. Sorry I do not have any Power right now (Electricians at work) so I cannot supply Logs.
But what I can say is that no apparent Process is running in the Background that is utilizing the CPU in any way.

**Comment by cebarks** [comment]
hmm, please share the logs when using the above PR when you can. In the mean time I've updated the database: https://github.com/RimSort/Steam-Workshop-Database/commit/c771abb4ef23a7e1ebfc7f8b7564461602c7bd9d

**Comment by cebarks** [comment]
If those of you getting this same error can confirm if you're building the database with local mods or from the steam workshop?

EDIT:

Hmm I just tried a local mods steamdb update and while the "This may take a while..." stage did take a while, it did finish.

**Comment by Skydea777** [comment]
@cebarks 

I did wait a while... as you can see:

`[DEBUG][2026-05-07 13:09:47][31520][MainThread][runner_panel][message][362] : Received valid Steam WebAPI key
[DEBUG][2026-05-07 13:09:47][31520][MainThread][runner_panel][message][362] : 
Initializing "DynamicQuery" with configured Steam API key for AppID: 294100


[DEBUG][2026-05-07 13:09:48][31520][MainThread][runner_panel][message][362] : IPublishedFileService/QueryFiles page [0/544]
[DEBUG][2026-05-07 13:09:48][31520][MainThread][runner_panel][message][362] : IPublishedFileService/QueryFiles page [1/544]
[...]
[DEBUG][2026-05-07 13:12:27][31520][MainThread][runner_panel][message][362] : IPublishedFileService/QueryFiles page [543/544]
[DEBUG][2026-05-07 13:12:27][31520][MainThread][runner_panel][message][362] : IPublishedFileService/QueryFiles page [544/544]
[DEBUG][2026-05-07 13:12:27][31520][MainThread][runner_panel][message][362] : 
Populated 54354 items queried from Steam Workshop into initial database for AppId 294100
[DEBUG][2026-05-07 13:12:28][31520][Dummy-43][wrapper][__initialize_webapi][302] : WebAPI is active!
[DEBUG][2026-05-07 13:12:28][31520][MainThread][runner_panel][message][362] : 
Steam WebAPI: IPublishedFileService/GetDetails initializing for 54348 mods


[DEBUG][2026-05-07 13:12:28][31520][MainThread][runner_panel][message][362] : IPublishedFileService/GetDetails chunk [0/54348]
[DEBUG][2026-05-07 13:12:28][31520][MainThread][runner_panel][message][362] : IPublishedFileService/GetDetails chunk [213/54348]
[DEBUG][2026-05-07 13:12:29][31520][MainThread][runner_panel][message][362] : IPublishedFileService/GetDetails chunk [426/54348]
[DEBUG][2026-05-07 13:12:30][31520][Dummy-43][wrapper][IPublishedFileService_GetDetails][534] : Could not find pfid 3718647902 in database. Adding child to missing_children
[...]
[DEBUG][2026-05-07 13:19:31][31520][Dummy-43][wrapper][IPublishedFileService_GetDetails][479] : Tried to parse metadata for a mod that is deleted/private/removed/unposted: 728318507
[DEBUG][2026-05-07 13:19:31][31520][Dummy-43][wrapper][IPublishedFileService_GetDetails][479] : Tried to parse metadata for a mod that is deleted/private/removed/unposted: 727581581
[DEBUG][2026-05-07 13:19:31][31520][Dummy-43][wrapper][IPublishedFileService_GetDetails][479] : Tried to parse metadata for a mod that is deleted/private/removed/unposted: 831157142
[DEBUG][2026-05-07 13:19:31][31520][MainThread][runner_panel][message][362] : IPublishedFileService/GetDetails chunk [54765/54765]
[DEBUG][2026-05-07 13:19:31][31520][MainThread][runner_panel][message][362] : 
AppID dependency retrieval enabled. Starting Steamworks API call(s)
[DEBUG][2026-05-07 13:19:31][31520][MainThread][runner_panel][message][362] : 
Steamworks API: ISteamUGC/GetAppDependencies initializing for 54765 mods

This may take a while. Please wait...
[INFO][2026-05-07 13:54:26][31520][MainThread][runner_panel][_do_save_runner_output][256] : Opening file dialog to specify output file
[INFO][2026-05-07 13:54:37][31520][MainThread][runner_panel][_do_save_runner_output][269] : Saving output to: C:\Users\...\database.txt
[INFO][2026-05-07 13:54:37][31520][MainThread][runner_panel][_do_save_runner_output][275] : Output successfully saved
[INFO][2026-05-07 19:36:01][31520][MainThread][main_content_panel][_open_in_default_editor][1607] : Opening file in default editor: C:\Users\...\AppData\Local\RimSort\Logs\RimSort.log`

EDIT:
Also, the Database.txt is just .. the log again:

[database.txt](https://github.com/user-attachments/files/27491066/database.txt)

**Comment by cebarks** [comment]
Hmm, that all looks correct. is `database.txt` just the name you chose instead of `steamDB.json`?

**Comment by Skydea777** [comment]
@cebarks 

No I choose a name with date and description, without any special characters besides underscore _ and without spaces in a completely different folder,  I do not know how the database txt came to be.

**Comment by Skydea777** [comment]
@cebarks 

Well.. I waited two hours...

<img width="1424" height="631" alt="Image" src="https://github.com/user-attachments/assets/8e4d1dee-1825-4172-b48b-dde972d1576e" />

EDIT:
The File was Empty and is Empty, no Files were saved.

**Comment by Skydea777** [comment]
Release 1.2.0

I am waiting now for now... 6 or 7 hours?

<img width="900" height="600" alt="Image" src="https://github.com/user-attachments/assets/225ff79d-81f6-4602-8e21-c5752de33713" />

@cebarks is there any update on what is happening here?

**Comment by cebarks** [comment]
Hmm I'm not having any luck reproducing this on my side and since there doesn't seem to be any errors occuring in your logs my best guess is that it's some kind of issue with your steam client not responding to the sdk correctly.

I'm working on a refactor that changes the way we integrate with the steamworks sdk, so once that is in a testable state we can see if that helps your problem. In the mean time i'll run a no_local database update and merge it to the repo.

**Comment by Skydea777** [comment]
@cebarks I have to agree that there must be some issues with the SDK because there are multiple people that have various issues with it.
As example, updating using RimSort which as far as I know also uses this, is right now pretty much impossible and yes I know that it is being worked on.
As a blind guess I would say some locale / language / region Issue, like .. USA <-> Germany, if you change the Regional Setting the Comma and Point are swapped for decimal places which CAUSES Issues with Industry Software.

**Comment by cebarks** [comment]
There are a few issues I've found in rimsort and in the underlying library we use, steamworkspy. 

One of the big issues in steamworkspy is that if too many sdk calls are made too quickly, the callback function is overridden with the most recent call so we don't always know if a sdk invocation failed or not. 

Another issue is the method rimsort currently uses to force download a mod, which is unsubscribing and then resubscribing to a mod, which can cause a de-sync between RimSort, the steam client, and the on-disk steam acf database. The fix here is to use a different SDK method: `DownloadItem` which forces steam to verify the mod files (or game files) and then check for an update.

There are a few other smaller issues but those are the big two I've run into.

**Comment by LionelColaso** [comment]
@cebarks the sync issue is due to watchdog not detecting the change in .acf file and updating the metadata and the acf data accordingly 

Edit : current fix to get away with it is to just hit Refresh button

**Comment by cebarks** [comment]
the steam client also doesn't immediately save changes to disk (anymore? or maybe ever? I've had a hard time finding consistent information on this online), which can also cause issues.

**Comment by LionelColaso** [comment]
> the steam client also doesn't immediately save changes to disk (anymore? or maybe ever? I've had a hard time finding consistent information on this online), which can also cause issues.

I have fixed it and have been testing it since some days just some minor tweaking remaining

**Comment by LionelColaso** [comment]
> Release 1.2.0
> 
> I am waiting now for now... 6 or 7 hours?
> <img alt="Image" width="900" height="600" src="https://private-user-images.githubusercontent.com/156956074/597317403-225ff79d-81f6-4602-8e21-c5752de33713.png?jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Nzk2MzI3NDEsIm5iZiI6MTc3OTYzMjQ0MSwicGF0aCI6Ii8xNTY5NTYwNzQvNTk3MzE3NDAzLTIyNWZmNzlkLTgxZjYtNDYwMi04ZTIxLWM1NzUyZGUzMzcxMy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjYwNTI0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI2MDUyNFQxNDIwNDFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0xNWE2OWU3OWI4NTBkZTYwMzc2MjRlNTkzZjU1N2E0MzA2YTIxYWQxN2M2YzM0ZWE4YTc4NWIzOTliMDc2OTY0JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZyZXNwb25zZS1jb250ZW50LXR5cGU9aW1hZ2UlMkZwbmcifQ.skJ7Pcga_r2GjdLHufrefgoZMsUqkDEG3F1Qhw8RAwU">
> 
> [@cebarks](https://github.com/cebarks) is there any update on what is happening here?

i could replicate your issue just to be sure i need to know where were you saving the database file

**Comment by LionelColaso** [comment]
Should be fixed in v1.2.2 check video for reference the video is not edited in any way 
 https://www.youtube.com/watch?v=pc9CXvgZ6UE 
if you encounter issues try the below and let me know if yo still have issue along with your OS, antivirus if any and settings you are using 
1) Turning off your antivirus it may detect RimSort steamDB building as malware behavior since it's generating a lot of data from steam
2) Make sure steam is not running when you building database can interfere with the process
3) Check path where you are saving the database can be written to by RimSort
4) Try Running as per these Settings 

<img width="1038" height="673" alt="Image" src="https://github.com/user-attachments/assets/ed5ad772-0fc0-42da-8564-b336b84c93bf" />

**Comment by cebarks** [comment]
@LionelColaso database still failing to build on macos when running from current main branch using the settings mentioned above. It still gets stuck on the steamworks api calls if steam is running, and if not, it skips them entirely 🙃

Without steam running (skips dlc lookup):
<img width="853" height="734" alt="Image" src="https://github.com/user-attachments/assets/b8ab6eb5-2e17-43ae-869c-878fe96139da" />

With steam running (hangs forever, no steamworks initialization in logs):
<img width="861" height="556" alt="Image" src="https://github.com/user-attachments/assets/60ba3096-4462-4554-982b-c8d40ff61ad7" />

**Comment by Skydea777** [comment]
@cebarks 
Oh sorry, I forgot to post, it still fails for me on Windows 11 25H2 and RimSort 1.2.2.

Same Issue, normal steps till "This may take a while. Please wait..." which leads even after 12 Hours of letting the PC run to... nothing.
Steam Downloads and missing Mods are still happening... so right now still everything... as always... since the start of the whole odyssey i could not play Rimworld, I am sad.

So yeah same old same old, nothing will happen after this point (ran on 1.2.2.):
======

<img width="902" height="632" alt="Image" src="https://github.com/user-attachments/assets/d8731e01-8d00-42dd-886e-a0d58f67f7bd" />

======

**Comment by cebarks** [comment]
> Same Issue, normal steps till "This may take a while. Please wait..." which leads even after 12 Hours of letting the PC run to... nothing. Steam Downloads and missing Mods are still happening... so right now still everything... as always... since the start of the whole odyssey i could not play Rimworld, I am sad.


You don't need to build the database yourself in order to use RimSort? The missing mods/steam downloads issues are separate to the issue with the steamDB build failing.

**Comment by Skydea777** [comment]
I know I don't need to and I know that all these are separate issues, it is just frustration for frustrations sake and wanted to mention that 1.2.2 did not fix the bug in creating the Database Locally, that is everything.

**Comment by Skydea777** [comment]
<img width="902" height="632" alt="Image" src="https://github.com/user-attachments/assets/3a258111-5e5b-471a-846b-c8ab5893a563" />

@cebarks @LionelColaso 

Good News Everyone. It took about two hours but the Database was created! - Rimworld 1.3.0

**Comment by cebarks** [comment]
let's gooooooo
