### ISSUE TITLE
Both topological and alphabetical sort don't always sort correctly

### ISSUE THREAD

**Issue by dbartussek** [RimSort/RimSort#662]
### Release Type

Compiled (Windows x86-64)

### Version

v1.0.11-edge7

### Operating System

Windows 11

### Relevant logs

http://0x0.st/XlhD.log

### Describe the bug

I've noticed this in particular with `Prepatcher`, `Harmony` and `HugsLib`.
`Prepatcher` has a "loadBefore" rule on `Harmony`, however the autosort always puts `Prepatcher` after `Harmony`:
![image](https://github.com/user-attachments/assets/6b01923f-d420-4ed6-868b-58922523d8f4)

`HugsLib` is also sometimes sorted before the base game, though this is not consistent. _Sometimes_ it will sort `HugsLib` correctly.
![image](https://github.com/user-attachments/assets/bb2feb71-112c-4c4c-bdd9-49433c9c605b)

This issue also seems to coincide with RimSort not realizing that there are unmet dependencies:
![image](https://github.com/user-attachments/assets/2a67e81e-c91e-4820-9879-4ad304acbcb8)
![image](https://github.com/user-attachments/assets/691df7ff-6491-4f09-a606-6efb30348b3f)

These images show two issues:
- `VFE Ancients - Vaults are Eternal` is a patch to `Vanilla Factions Expanded - Ancients` and has it listed as a dependency, so the first image should show an error message
- `VFE Ancients - Vaults are Eternal` may not be sorted before `Vanilla Factions Expanded - Ancients` because of a "loadAfter" rule in `VFE Ancients - Vaults are Eternal`

The rule editor also shows this dependency, so at least some part of RimSort does know about it:
![image](https://github.com/user-attachments/assets/519a38f4-672a-437b-990f-47fd9719848e)

Oddly enough, I _have_ gotten RimSort to realize that `VFE Ancients - Vaults are Eternal` on its own is missing dependencies, but I have no idea how I did it, it didn't persist through a RimSort restart and I couldn't replicate it for this bug report.

Looking through the log file, there seem to be some issues in the metadata handling. I have also attached a separate log file with debug logging enabled:
[RimSort.log](https://github.com/user-attachments/files/17482503/RimSort.log)

### Code of Conduct

I agree to follow this project's Code of Conduct

### Duplicate Issue Check

I've checked for similar issues and didn't find anything

### Wiki/FAQ Check

I've checked the Wiki for a solution and didn't find a solution

**Comment by hk21702** [comment]
I think this has been reported a number of times and your conclusion that it has to do with metadata seems to be correct. There is a complete rework of how metadata is handled in the works right now that will prob be ready in the next next release if I had to guess. For now though, I've seen that stuff like this gets resolved in weird ways such as just spamming refresh, restarting rimsort, etc., though no definitive reports of how it gets resolved.

**Comment by LionelColaso** [comment]
Try enabling  `Use dependencies rules for sorting`
Reopen the issue if problem still exists with latest version of RimSort
![Image](https://github.com/user-attachments/assets/65708d8a-6978-46fd-b8b8-a4f990c311b4)
